--ERROR 17002
----1. run cmd admin privileges
----2. lsnrctl start

drop table otm_aeroporto;
drop table otm_voo;

--Tables--

create table otm_aeroporto(
  idaeroporto number generated by default on null as identity,
	pais varchar2(30) not null,
  cidade varchar2(30) not null,
  nome varchar2(50) not null,
  latitude decimal(9,6) not null,
  longitude decimal(9,6) not null
	);
  
create table otm_voo(
  idvoo number generated by default on null as identity,
	codigovoo number,
  codigocompanhia varchar2(10),
  partidaaeroportoid number,
  chegadaaeroportoid number,
  partidacidade varchar2(30),
  chegadacidade varchar2(30),
  partidatempoestimado date,
  chegadatempoestimado date,
  partidatemporeal date,
  chegadatemporeal date
	);
  

insert into otm_aeroporto(pais,cidade,nome,latitude,longitude) values('Portugal', 'Porto', 'Francisco Sá Carneiro', 41.248100, -8.681389);
insert into otm_aeroporto(pais,cidade,nome,latitude,longitude) values('Portugal', 'Lisboa', 'Portela', -12.808899, 15.7605);

insert into otm_voo(codigovoo,codigocompanhia,partidaaeroportoid,chegadaaeroportoid,partidacidade,chegadacidade,partidatempoestimado,chegadatempoestimado,partidatemporeal,chegadatemporeal) values(10001, 'TAP', 1, 2, 'Porto', 'Lisboa', to_date('2014/05/04:13:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:14:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:13:30', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:14:30', 'yyyy/mm/dd:hh24:mi'));
insert into otm_voo(codigovoo,codigocompanhia,partidaaeroportoid,chegadaaeroportoid,partidacidade,chegadacidade,partidatempoestimado,chegadatempoestimado,partidatemporeal,chegadatemporeal) values(10002, 'TAP', 1, 2, 'Porto', 'Lisboa', to_date('2014/05/04:14:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:15:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:14:30', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:15:30', 'yyyy/mm/dd:hh24:mi'));
insert into otm_voo(codigovoo,codigocompanhia,partidaaeroportoid,chegadaaeroportoid,partidacidade,chegadacidade,partidatempoestimado,chegadatempoestimado,partidatemporeal,chegadatemporeal) values(10003, 'TAP', 2, 1, 'Lisboa', 'Porto', to_date('2014/05/04:14:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:15:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:14:30', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:15:30', 'yyyy/mm/dd:hh24:mi'));
insert into otm_voo(codigovoo,codigocompanhia,partidaaeroportoid,chegadaaeroportoid,partidacidade,chegadacidade,partidatempoestimado,chegadatempoestimado,partidatemporeal,chegadatemporeal) values(10004, 'TAP', 2, 1, 'Lisboa', 'Porto', to_date('2014/05/04:15:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:16:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:15:30', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:16:30', 'yyyy/mm/dd:hh24:mi'));
select * from otm_aeroporto;
select * from otm_voo;

