--ERROR 17002
----1. run cmd admin privileges
----2. lsnrctl start

drop table otm_aeroporto;
drop table otm_voo;
drop table otm_contacto;
drop table otm_contacto_telefone;

drop table otm_servico;
drop table otm_mapa;

--Tables--

create table otm_aeroporto(
  idaeroporto number generated by default on null as identity,
	pais varchar2(30) not null,
  cidade varchar2(30) not null,
  nome varchar2(50) not null,
  latitude decimal(9,6) not null,
  longitude decimal(9,6) not null
	);
  
create table otm_voo(
  idvoo number generated by default on null as identity,
	codigovoo number,
  codigocompanhia varchar2(10),
  partidaaeroportoid number,
  chegadaaeroportoid number,
  partidacidade varchar2(30),
  chegadacidade varchar2(30),
  partidatempoestimado date,
  chegadatempoestimado date,
  partidatemporeal date,
  chegadatemporeal date
	);
  
create table otm_contacto(
  idcontacto number generated by default on null as identity,
  idaeroporto number,
  nome varchar(50),
  titulo varchar(50),
  website varchar(50),
  mapaurl varchar(50),
  descricao varchar(50)
);

create table otm_contacto_telefone(
  idtelefone number generated by default on null as identity,
  idcontacto number,
  contacto number
);

create table otm_servico(
  idservico number generated by default on null as identity,
  idaeroporto number,
  nome varchar(50),
  descricao varchar(50)
);

create table otm_mapa(
  idmapa number generated by default on null as identity,
  idservico number,
  localizacao varchar(50),
  url varchar(50)
);

insert into otm_aeroporto(pais,cidade,nome,latitude,longitude) values('Portugal', 'Porto', 'Francisco Sá Carneiro', 41.248100, -8.681389);
insert into otm_aeroporto(pais,cidade,nome,latitude,longitude) values('Portugal', 'Lisboa', 'Portela', -12.808899, 15.7605);

insert into otm_voo(codigovoo,codigocompanhia,partidaaeroportoid,chegadaaeroportoid,partidacidade,chegadacidade,partidatempoestimado,chegadatempoestimado,partidatemporeal,chegadatemporeal) values(10001, 'TAP', 1, 2, 'Porto', 'Lisboa', to_date('2014/05/04:13:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:14:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:13:30', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:14:30', 'yyyy/mm/dd:hh24:mi'));
insert into otm_voo(codigovoo,codigocompanhia,partidaaeroportoid,chegadaaeroportoid,partidacidade,chegadacidade,partidatempoestimado,chegadatempoestimado,partidatemporeal,chegadatemporeal) values(10002, 'TAP', 1, 2, 'Porto', 'Lisboa', to_date('2014/05/04:14:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:15:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:14:30', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:15:30', 'yyyy/mm/dd:hh24:mi'));
insert into otm_voo(codigovoo,codigocompanhia,partidaaeroportoid,chegadaaeroportoid,partidacidade,chegadacidade,partidatempoestimado,chegadatempoestimado,partidatemporeal,chegadatemporeal) values(10003, 'TAP', 2, 1, 'Lisboa', 'Porto', to_date('2014/05/04:14:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:15:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:14:30', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:15:30', 'yyyy/mm/dd:hh24:mi'));
insert into otm_voo(codigovoo,codigocompanhia,partidaaeroportoid,chegadaaeroportoid,partidacidade,chegadacidade,partidatempoestimado,chegadatempoestimado,partidatemporeal,chegadatemporeal) values(10004, 'TAP', 2, 1, 'Lisboa', 'Porto', to_date('2014/05/04:15:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:16:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:15:30', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:16:30', 'yyyy/mm/dd:hh24:mi'));
insert into otm_voo(codigovoo,codigocompanhia,partidaaeroportoid,chegadaaeroportoid,partidacidade,chegadacidade,partidatempoestimado,chegadatempoestimado,partidatemporeal,chegadatemporeal) values(10005, 'TAP', 3, 1, 'Madrid', 'Porto', to_date('2014/05/04:14:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:15:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:14:30', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:15:30', 'yyyy/mm/dd:hh24:mi'));
insert into otm_voo(codigovoo,codigocompanhia,partidaaeroportoid,chegadaaeroportoid,partidacidade,chegadacidade,partidatempoestimado,chegadatempoestimado,partidatemporeal,chegadatemporeal) values(10006, 'TAP', 3, 1, 'Madrid', 'Porto', to_date('2014/05/04:15:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:16:35', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:15:30', 'yyyy/mm/dd:hh24:mi'), to_date('2014/05/04:16:30', 'yyyy/mm/dd:hh24:mi'));

insert into otm_contacto(idaeroporto,nome,titulo,mapaurl,website,descricao) values(1,'taxis','Táxis','http://i.imgur.com/o4QFmdH.png','www.taxisporto.com','Táxis do Porto');
insert into otm_contacto(idaeroporto,nome,titulo,mapaurl,website,descricao) values(2,'taxis','Táxis','http://i.imgur.com/o4QFmdH.png','www.taxislisboa.com','Táxis do Porto');
insert into otm_contacto_telefone(idcontacto,contacto) values(1,351220997336);
insert into otm_contacto_telefone(idcontacto,contacto) values(1,351918888600);
insert into otm_contacto_telefone(idcontacto,contacto) values(1,351965886532);
insert into otm_contacto_telefone(idcontacto,contacto) values(1,351933544838);
insert into otm_contacto_telefone(idcontacto,contacto) values(2,351219362113);

insert into otm_servico(idaeroporto,nome,descricao) values(1,'restaurantes','Restaurantes');
insert into otm_mapa(idservico,localizacao,url) values(1,'Chegadas','http://i.imgur.com/WBmmCjo.png');

insert into otm_servico(idaeroporto,nome,descricao) values(1,'wc','WC');
insert into otm_mapa(idservico,localizacao,url) values(2,'Chegadas','http://i.imgur.com/1znrmtG.png');
insert into otm_mapa(idservico,localizacao,url) values(2,'Embarque','http://i.imgur.com/8eM6duf.png');
insert into otm_mapa(idservico,localizacao,url) values(2,'Partidas','http://i.imgur.com/DOuZF1D.png');

insert into otm_servico(idaeroporto,nome,descricao) values(1,'apoio','Apoio Cliente');
insert into otm_mapa(idservico,localizacao,url) values(3,'Chegadas','http://i.imgur.com/RYATv4Q.png');
insert into otm_mapa(idservico,localizacao,url) values(3,'Embarque','http://i.imgur.com/iuRHJKK.png');
insert into otm_mapa(idservico,localizacao,url) values(3,'Partidas','http://i.imgur.com/n9puYOq.png');

--insert into otm_servico(idaeroporto,nome) values(2,'restaurantes');
--insert into otm_mapa(idservico,localizacao,url) values(2,'Chegadas','http://i.imgur.com/WBmmCjo.png');

--select * from otm_aeroporto;
--select * from otm_voo;
--select * from otm_taxi where idaeroporto = 1;
--select * from otm_taxi_contacto where idtaxi = 1;
--select * from otm_servico where nome = 'restaurante';
--select * from otm_mapa where idservico = 1;
select * from otm_servico where nome = 'restaurantes' and idaeroporto = 1;
select * from otm_mapa where idservico = 1;
