--ERROR 17002
----1. run cmd admin privileges
----2. lsnrctl start

drop table otm_contact;

--Tables--
  
create table otm_contact(
  idcontact number generated by default on null as identity,
  airportcode varchar(5),
  type varchar(50),
  code varchar(50),
  email varchar(50),
  facebook varchar(50),
  telef varchar(50),
  twitter varchar(50),
  website varchar(50),
  logourl varchar(300)
);

--Servicos

insert into otm_contact(airportcode,type,code,email,telef,website) values('OPO','Taxi','T1','servicostaxisinvicta@taxisporto.com','+351 220 997 336','http://www.taxisporto.com');
insert into otm_contact(airportcode,type,code,email,telef,website,logourl,facebook) values('OPO','Shop','S1','contact@bimbaylola.com','+34 986 288 401','http://www.bimbaylola.com','http://www.bimbaylola.com/img/logo_portada.jpg','https://www.facebook.com/BimbayLolaOfficial');
insert into otm_contact(airportcode,type,code,email,telef,website,logourl) values('OPO','Shop','S2','info@boutiquedosrelogios.pt','+351 218 311 243','http://www.boutiquedosrelogios.pt','http://www.boutiquedosrelogios.pt/cache/1000098.png');
insert into otm_contact(airportcode,type,telef) values('OPO','RescueStation','+351 229 432 400');
insert into otm_contact(airportcode,type,telef) values('OPO','LostAndFound','+351 229 432 400');




select * from otm_contact;